// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qfkmekydndlkihqbwujy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFma21la3lkbmRsa2locWJ3dWp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3MDM4NTMsImV4cCI6MjA2NTI3OTg1M30.H3Zkjh0vOw-9R7nftwPo1htkBv_jzUGBDe16pk9BMzw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);